// pages/index.vue
<template>
  <div>
    <div class="container">
      <div class="mt-20 items-center">
        <h1 class="text-6xl w-full text-center font-semibold items-center">
          Discord Moderation at your fingertips.
        </h1>
        <p class="font-light mt-6 mx-auto w-full lg:w-1/2 text-center text-3xl">
          Launching in mid-late 2021, dmod will be the platform for Server
          Owners and Moderators alike.
        </p>
      </div>
    </div>

    <div class="container">
      <div
        class="lg:flex lg:flex-row lg:flex-no-wrap lg:mt-20 md:items-center md:flex-row md:flex"
      >
        <div
          class="w-full lg:w-8/12 lg:mr-16 flex flex-wrap lg:flex-nowrap justify-between items-start lg:mb-5"
        >
          <div class="p-8 lg:w-10/12 mr-auto lg:mt-40">
            <h1 class="text-4xl font-semibold text-left">
              Goodbye Google Forms.
            </h1>
            <p class="text-2xl font-light mt-2 text-left">
              With Dmod, finding moderators or a server to work for has never
              been quicker! Create or apply for Applications. Even search by
              Rating, Time Zone, and more.
            </p>
          </div>
        </div>
        <div
          class="mt-6 mr-8 hidden sm:hidden md:block lg:block xl:block 2xl:block"
        >
          <img src="~/assets/img/google-forms.svg" alt="" class="lg:h-80" />
        </div>
      </div>
      <div
        class="lg:flex lg:flex-row lg:flex-no-wrap lg:mt-20 md:items-center md:flex-row md:flex"
      >
        <div
          class="w-full lg:w-8/12 lg:mr-16 flex flex-wrap lg:flex-nowrap justify-between items-start lg:mb-5"
        >
          <div class="p-8 lg:w-10/12 mr-auto lg:mt-40">
            <h1 class="text-4xl font-semibold text-left">
              Made by Discord Users, for Discord Users.
            </h1>
            <p class="text-2xl font-light mt-2 text-left">
              As Moderators and Server Owners, we’re always looking for tools
              that can others in the community out. We hope Dmod will become a
              helpful tool.
            </p>
          </div>
        </div>
        <div
          class="mt-6 mr-8 hidden sm:block md:block lg:block xl:block 2xl:block"
        >
          <img src="~/assets/img/users.svg" alt="" class="lg:h-80" />
        </div>
      </div>
      <div
        class="lg:flex lg:flex-row lg:flex-no-wrap lg:mt-20 md:items-center md:flex-row md:flex"
      >
        <div
          class="w-full lg:w-8/12 lg:mr-16 flex flex-wrap lg:flex-nowrap justify-between items-start lg:mb-5"
        >
          <div class="p-8 lg:w-10/12 mr-auto lg:mt-40">
            <h1 class="text-4xl font-semibold text-left">
              Are you a Moderator? We got you covered.
            </h1>
            <p class="text-2xl font-light mt-2 text-left">
              Create and Customize your profile, get your own Vanity URL, fill
              in past experience and all sorts of info, and inquire for
              positions.
            </p>
          </div>
        </div>
        <div
          class="mt-6 mr-8 hidden sm:block md:block lg:block xl:block 2xl:block"
        >
          <img src="~/assets/img/mod.svg" alt="" class="lg:h-80" />
        </div>
      </div>
      <div
        class="lg:flex lg:flex-row lg:flex-no-wrap lg:mt-20 md:items-center md:flex-row md:flex"
      >
        <div
          class="w-full lg:w-8/12 lg:mr-16 flex flex-wrap lg:flex-nowrap justify-between items-start lg:mb-5"
        >
          <div class="p-8 lg:w-10/12 mr-auto lg:mt-40">
            <h1 class="text-4xl font-semibold text-left">
              Are you a Server Owner? Dmod is for you too.
            </h1>
            <p class="text-2xl font-light mt-2 text-left">
              Server Owners have been wasting time using random tools for way
              too long. Here, you can create forms, share them with a Vanity
              URL, and collect responses, write mod reviews, all made to help
              Server Owners.
            </p>
          </div>
        </div>
        <div
          class="mt-6 mr-8 hidden sm:block md:block lg:block xl:block 2xl:block"
        >
          <img src="~/assets/img/owner.svg" alt="" class="lg:h-80" />
        </div>
      </div>
      <!-- looking forward to launch section -->
    </div>
  </div>
</template>

<script>
export default {};
</script>

// pages/index.tsx
import Footer from '@components/Footer';

export default function Home() {
	return (
		<>
			<main>
				<div className='top'>
					<h1>Discord Moderation at your fingertips!</h1>
					<p>
						Launching in mid-late 2021, dmod will be the platform for Server
						Owners and Moderators alike.
					</p>
				</div>
				<div className='right'>
					<div>
						<h2>Goodbye Google Forms.</h2>
						<p>
							With Dmod, finding moderators or a server to work for has never
							been quicker! Create or apply for Applications. Even search by
							Rating, Time Zone, and more.
						</p>
					</div>
					<img src='/form.svg' />
				</div>
				<div className='left'>
					<div>
						<h2>
							Made by Discord Users, <br />
							for Discord Users.
						</h2>
						<p>
							As Moderators and Server Owners, we’re always looking for tools
							that can others in the community out. We hope Dmod will become a
							helpful tool.
						</p>
					</div>
					<img src='/users.svg' />
				</div>
				<div className='right'>
					<div>
						<h2>
							Are you a Moderator? <br />
							We've got you covered.
						</h2>
						<p>
							Create and Customize your profile, get your own Vanity URL, fill
							in past experience and all sorts of info, and inquire for
							positions.
						</p>
					</div>
					<img src='/mod.svg' />
				</div>
				<div className='left'>
					<div>
						<h2>
							Are you a Server Owner? <br />
							Dmod is for you, too.
						</h2>
						<p>
							Server Owners have been wasting time using random tools for way
							too long. Here, you can create forms, share them with a Vanity
							URL, and collect responses, write mod reviews, all made to help
							Server Owners.
						</p>
					</div>
					<img src='/owner.svg' />
				</div>
			</main>
			<Footer />
		</>
	);
}
